### ISSUE TITLE
Bug Report: Update issue

### ISSUE THREAD

**Issue by StanerGaming** [YoshiCrafter29/CodenameEngine#24] opened 2022-12-24 19:58 UTC
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

Kinda new to this github stuff, so I'll just write the issue

So I installed the latest build, compiled the thing and everything went well. I ran the engine for the first time and did the update thing.

After the update though, game opened and crashed with "can't delete codenameengine.bak" or something like that.

I opened it again and it opened with beta build 1586, and always pops up the update thing. I press update, and wait for it to finish, and when it finishes it just closes and opens the same build again and then rinse and repeat.

Here'a video of my issue: 

https://user-images.githubusercontent.com/71552528/209449607-801740ea-da46-4f3c-a692-41b9750895cb.mp4

I don't know if this is an actual bug or if I'm just dumb lol

**Comment by FoxelTheFennic** [comment] 2022-12-25 00:26
![image](https://user-images.githubusercontent.com/75647306/209453881-9e286448-aca9-4b51-bb92-52204c64bc86.png)
dont update the engine (its supposed to say "AS ALWAYS, SKIP", no idea why its cut off like that)

(also, to fix just rebuild the game)

**Comment by YoshiCrafter29** [comment] 2022-12-25 02:27
"AS ALWAYS, SKIP" is here for a reason.
Basically, by updating, you're downloading a much older build of Codename Engine, which has that cut off bug that was fixed in the latest versions.

Not a bug, closing.

**Closed by YoshiCrafter29** 2022-12-25 02:27 UTC
Labels: bug

**Comment by StanerGaming** [comment] 2022-12-25 13:07
Thanks for the help.
